### ISSUE TITLE
Permissions for commands. 

### ISSUE THREAD

**Issue by jonahzs** [ITheEqualizer/EqualizerBot#6]
**Is your feature request related to a problem? Please describe.**
Adding a permissions feature for commands - Simply put, some commands that anyone can use should be configurable to only certain roles. 
**Describe the solution you'd like**
Custom permissions for roles - Like giving them permissions to certain commands.
**Describe alternatives you've considered**
There really are not a lot of alternatives other than choosing a different bot, or letting members use all of the commands.
**Additional context**
No additional context needed. However if you are interested I am able to lay out some basic code that might work.

**Comment by ITheEqualizer** [comment]
This might be added in the feature, There is no ETA.
